type User{
    id: ID!
    name: String! 
    email: String!
}

type Query{
    getUser(id:ID!):User
}

input CreateUserInput{
    name: String!
    email: String!
}

type Mutation{
    createUser(input:CreateUserInput):User!
}