type User{
    id : ID!
    email: String!
    firstName: String!
    lastName: String!
}

type Query{
    getUser(id:ID!):User
}

input CreateUserInput{
    email: String!
    firstName: String!
    lastName: String!
}

type Mutation{
    createUser(input:CreateUserInput):User!
}